format_version: 2
environments:
  ci:
    pipelines:
      - "team2UI"

pipelines:
  "team2UI":
    group: team2
    materials:
      ui:
        git: "https://github.com/vnsam/cricket-scorer-ui-nobackend.git"
    stages:
      - test:
          jobs:
            test:
              resources:
                - node-and-java
              tasks:
                - script: |
                    yarn install
                    yarn run ci
      - build:
          jobs:
            build:
              resources:
                - node-and-java
              tasks:
                - script: |
                    yarn install
                    yarn run build
      - deploy:
          jobs:
            deploy:
              resources:
                - node-and-java
              tasks:
                - script: |
                    sh ./buildAndDeploy/deploy.sh team2-bootcamp-august2018
